### PR TITLE
Removes deprecated functions to test pull request analysis.

### PR DESCRIPTION
**Pull request by kevinsmeets**

### CODE REVIEW

**Comment by kevinsmeets** [comment]
retest this please

**Comment by kevinsmeets** [comment]
retest this please

**Comment by villgust** [comment]
retest this please

**Comment by villgust** [comment]
retest this please

**Comment by villgust** [comment]
retest this please

**Comment by villgust** [comment]
retest this please

**Comment by robindenadel** [comment]
retest this please

**Comment by robindenadel** [comment]
retest this please

**Comment by robindenadel** [comment]
retest this please

**Comment by villgust** [comment]
retest this please

**Comment by villgust** [comment]
retest this please

**Comment by villgust** [comment]
retest this please

**Comment by kevinsmeets** [comment]
retest this please

**Comment by kevinsmeets** [comment]
retest this please

**Comment by kevinsmeets** [comment]
retest this please

**Pull request closed without merging**
